# Generated by Django 4.2.16 on 2024-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('note_progression', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
