# Generated by Django 4.2.16 on 2024-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tune',
            name='note_progression',
            field=models.CharField(max_length=120),
        ),
    ]
